version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: proctor-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: proctor-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo-data:
